name: hi_tech_pantry
description: "An application to manage your pantry and shopping list."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  qr_flutter: ^4.1.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  fluttertoast: ^8.2.8
  provider: ^6.1.2
  go_router: ^14.3.0
  intl: ^0.19.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.0
  bad_words: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
