name: barcode_scan_app
description: "Hi-Tech Pantry"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dart_firebase_admin: ^0.4.0
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/service_account/credentials.json